/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AprenderRouteImport } from './routes/aprender'
import { Route as ExamenRouteImport } from './routes/examen'
import { Route as PersonalizadaRouteImport } from './routes/personalizada'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderRoute = AprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamenRoute = ExamenRouteImport.update({
  id: '/examen',
  path: '/examen',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizadaRoute = PersonalizadaRouteImport.update({
  id: '/personalizada',
  path: '/personalizada',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/examen': typeof ExamenRoute
  '/personalizada': typeof PersonalizadaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/examen': typeof ExamenRoute
  '/personalizada': typeof PersonalizadaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/examen': typeof ExamenRoute
  '/personalizada': typeof PersonalizadaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aprender' | '/examen' | '/personalizada'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aprender' | '/examen' | '/personalizada'
  id: '__root__' | '/' | '/aprender' | '/examen' | '/personalizada'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprenderRoute: typeof AprenderRoute
  ExamenRoute: typeof ExamenRoute
  PersonalizadaRoute: typeof PersonalizadaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender': {
      id: '/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AprenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examen': {
      id: '/examen'
      path: '/examen'
      fullPath: '/examen'
      preLoaderRoute: typeof ExamenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizada': {
      id: '/personalizada'
      path: '/personalizada'
      fullPath: '/personalizada'
      preLoaderRoute: typeof PersonalizadaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprenderRoute: AprenderRoute,
  ExamenRoute: ExamenRoute,
  PersonalizadaRoute: PersonalizadaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
